spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.0.52:3306/tale?useUnicode=true&characterEncoding=UTF-8
    username: devuser
    password: devuser
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat=true

  jpa:
    database: MYSQL
    show-sql: true
  #Hibernate ddl auto (validate|create|create-drop|update)
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  thymeleaf:
    cache: false
  #maxfilesize  指定上传文件允许的最大大小 默认1M  maxRequestSize:指定允许表单请求的最大数据大小默认10M
  http:
    multipart:
      max-file-size: 5MB
      max-request-size: 15MB
server:
  port: 8888
  tomcat:
    uri-encoding: UTF-8
  context-path: /
#七牛的存储
qiniu:
  imgSpace: ycimgs
  AK: sj0iFkqo-dmmFz3u6KkKuBDqRxI4EVqnVUn7I2U_
  SK: 7ejmThWZQCTrJnKOU5y8-5B2RNLWiGPeADWU95Co
#url 的权限访问。#一些资源没有配置权限访问例如：show操作没有
#配置什么角色可以访问，那么它可以被所有的用户的访问。
securityconfig:
  openway: yml #取值（yml代表配置文件读取权限信息，sql代表从数据库读取权限信息）
  logoutsuccssurl: /
  permitall: /rest/**,/bbs**,/login
  deniedpage: /deny
  #这里需要配置较详细的权限。注意权限不能互斥
  urlroles: /role/index = admin;
            /role/add = admin;
            /role/edit/* = sa;
            /role/delete/** = sa;
            /order/delete/** = admin


